// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package slice

import "github.com/ozoncp/ocp-course-api/api/model"

// Converts the slice xs to map with the type of slice value as a value and the
// result of op as a key. If the op returns the same result for some values,
//the resulting map includes the latest value.
func ToMapModelCourseUint64(xs []model.Course, op func(model.Course) uint64) map[uint64]model.Course {
	res := make(map[uint64]model.Course, len(xs))
	for _, v := range xs {
		res[op(v)] = v
	}
	return res
}

// Converts the slice xs to map with the type of slice value as a value and the
// result of op as a key. If the op returns the same result for some values,
//the resulting map includes the latest value.
func ToMapModelLessonUint64(xs []model.Lesson, op func(model.Lesson) uint64) map[uint64]model.Lesson {
	res := make(map[uint64]model.Lesson, len(xs))
	for _, v := range xs {
		res[op(v)] = v
	}
	return res
}
