// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package repo

import "github.com/ozoncp/ocp-course-api/internal/api/model"

type RepoModelCourse interface {
	Describe(id uint64) (model.Course, error)
	List(limit uint64, offset uint64) ([]model.Course, error)
	Add(v model.Course) (uint64, error)
	Adds(vs []model.Course) error
	Remove(id uint64) error
	Update(v model.Course) error
}

type RepoModelLesson interface {
	Describe(id uint64) (model.Lesson, error)
	List(limit uint64, offset uint64) ([]model.Lesson, error)
	Add(v model.Lesson) (uint64, error)
	Adds(vs []model.Lesson) error
	Remove(id uint64) error
	Update(v model.Lesson) error
}
