// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package repo

import "github.com/ozoncp/ocp-course-api/api/model"

type RepoModelCourse interface {
	AddModelCourse(v model.Course) (uint64, error)
	AddModelCourses(vs []model.Course) error
}

type RepoModelLesson interface {
	AddModelLesson(v model.Lesson) (uint64, error)
	AddModelLessons(vs []model.Lesson) error
}
